version: '3.7'
services:
  mongodb:
    container_name: mongodb
    image: docker.io/bitnami/mongodb:latest
    restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=pruebatecnica
    ports:
      - 27017:27017

  mongoexpress:
    container_name: mongoexpress
    image: mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb-dev
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  postgresql:
    container_name: postgresql
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8083:80"
    depends_on:
      - postgresql
    